fetch_reviews:
  query: |
    with get_parent_part_number as (
      select 
        distinct parent_product_part_number as sku
      from edldb.chewybi.products
      where product_part_number = '{sku}'
    )
    select 
      cpr.PRODUCT_PART_NUMBER as sku,
      REVIEW_TXT as customer_review,
      RATING as product_rating,
      submission_tm as created_date,
      products.product_merch_classification1 as mc1,
      products.product_merch_classification2 as mc2,
      products.product_merch_classification3 as mc3,
      products.product_description_short,
      products.product_name as product_name,
      products.product_id,
      'https://www.chewy.com/'||pdpslug||'/dp/'||product_id as product_link
    from edldb.cdm.customer_product_rating as cpr
    JOIN edldb.chewybi.products AS products
        ON cpr.product_part_number = products.product_part_number
    where 1=1
    and cpr.PRODUCT_PART_NUMBER = (select sku from get_parent_part_number)
    and products.product_type ilike 'product'
    and moderation_status ilike 'APPROVED'
